bases:
- https://github.com/sbose78/taxi/deploy/templates?ref=master
configMapGenerator:
- name: stage-www-files
  files:
  - index.html
  - staging.html
images:
- name: quay.io/shbose/taxi
  newTag: 9259aa
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: taxi
  path: staging_patch.yaml
